import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '@styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main >
        <h1>Hyper Bros. Trading Cards</h1>
        <h2>Available Cards</h2>
        <ul className={styles.products}>
          <li><img src="/static/images/bowser.jpg" alt="bowser" /> <h3>Bowser Holographic</h3> <p>$99.99</p></li>
<li><img src="/static/images/bowser.jpg" alt="bowser" /> <h3>Bowser Holographic</h3> <p>$99.99</p></li>
<li><img src="/static/images/bowser.jpg" alt="bowser" /> <h3>Bowser Holographic</h3> <p>$99.99</p></li>
<li><img src="/static/images/bowser.jpg" alt="bowser" /> <h3>Bowser Holographic</h3> <p>$99.99</p></li>
        </ul>
      </main>

      <footer className={styles.footer}>
        &copy; Store, {new Date().getFullYear()}
      </footer>
    </div>
  )
}
